name: "fabric-network"
version: "1.0.0"

channels:
  channel1:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
    participants:
      - Doctor1
      - Doctor2
      - Doctor3
      - Staff1

  channel2:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
    participants:
      - Doctor1
      - Doctor2
      - Doctor3
      - Pharmacist1

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

orderers:
  orderer.example.com:
    url: grpc://localhost:7050

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
